### ISSUE TITLE
Getting errors for web build

### ISSUE THREAD

**Issue by songproducer** [haorendashu/nostrmo#4]
```
GET file:///assets/packages/flutter_inappwebview/assets/web/web_support.js net::ERR_FILE_NOT_FOUND
```

```
flutter.js:3    
       GET file:///Users/leotreasure/nostrmo/web/$FLUTTER_BASE_HREF/main.dart.js net::ERR_FILE_NOT_FOUND
```

```flutter.js:3 Exception while loading service worker: TypeError: Failed to register a ServiceWorker: The URL protocol of the current origin ('null') is not supported.
    at g.loadServiceWorker (flutter.js:3:315)
    at v.loadEntrypoint (flutter.js:3:2459)
    at index.html:62:23    ```

**Comment by haorendashu** [comment]
Thanks. It has bean fix and release just now.
